### ISSUE TITLE
Default user and root password

### ISSUE THREAD

**Issue by probonopd** [furybsd/furybsd-livecd#149]
The way the default user and root password are set up on the Live ISO is currently more complicated than on, say, an Ubuntu Live ISO:

* Users need to know the default password for `liveuser` (which happens to be `furybsd` respectively `furzbsd` on my German keyboard)
* Users need to know the default password for `root` (which happens to be `furybsd` respectively `furzbsd` on my German keyboard)
* Unlike on e.g., Ubuntu Live ISOs, `sudo su` respectively `runas` do not work passwordless for `liveuser`

Here is an example use case that I just encountered:
* Boot the Live ISO
* Double click "Configure Xorg" and select Nvidia
* After Xorg gets killed, the user is asked for a password they don't know (or at least I didn't at the time - I think I had tried `furybsd` which didn't work for me; perhaps I would have needed to type `furzbsd` on my German keyboard...)
* Alt-F1 brings up an entirely garbled console at this point on my system, so I cannot change the user password from there either
* Root cannot log into a graphical session
* This effectively locked me out of the computer, with my only option to power cycle the machine

On Ubuntu Live ISOs the default user does not have a password, can log into the desktop without a password, and can use `sudo su` to become root without a password. I think this solution would be more user friendly than the current hardcoded root password.

**Comment by pkgdemon** [comment]
This is somewhat improved for xfce in zstd branch.  I’ve been playing with the idea of making xfce the only published image while leaving others in the build system for those who wish to fork the project or contribute and publish their own versions.  Anyway my thought process was that using sddm vs lightdm would not require login after installing a xorg driver.  Also I should just ship a default sudo config already.  I wanted to avoid to many overlays because I want to redo how it works in a major way but your right that would have a lot of impact short term.  So I’ll keep that in mind.  I’ve also considered making the user create these passwords on first boot themselves before the desktop opens but I kind of like the Ubuntu experience myself.

**Comment by probonopd** [comment]
As for Ubuntu, you can even set your own username, timezone, keyboard layout and whatnot as a boot-time command line option. Which makes it handy to apply some default values in scripted boot scenarios like mine:

!()[https://user-images.githubusercontent.com/2480569/32960053-e1b345d4-cbc3-11e7-9f34-c1cc11b5b1c7.png]

**Comment by pkgdemon** [comment]
I do really kind of like the idea of password less root, and user actually for livecd with liveuser able to sudo to root out of box.  I think I'll escalate this one sooner rather than later.

**Comment by probonopd** [comment]
Possibly no passwords for root and liveuser, together with the following `/usr/local/etc/doas.conf` might do?

```                        
permit nopass keepenv :wheel
permit nopass keepenv root
```

**Comment by probonopd** [comment]
I have made a custom Live ISO with this. It seems to work for me.

**Comment by pkgdemon** [comment]
> Possibly no passwords for `root` and `liveuser`, together with the following `/usr/local/etc/doas.conf` might do?
> 
> ```
> permit nopass keepenv :wheel
> permit nopass keepenv root
> ```
> 
> During installation to disk, this `/usr/local/etc/doas.conf` could be undone if so desired.

Thank you for this.  FYI doas was only included because I was using networkmgr for a time.  We could switch to sudo as the default or offer both?  I'm more wired to typing sudo myself.

**Comment by probonopd** [comment]
People coming from the Linux world will know `sudo` but not `doas`. Is `doas` "the BSD way" of doing this? (That's what I was assuming here.)

**Comment by pkgdemon** [comment]
Doas is not necessarily the bsd way of doing sudo. It's something that has grown popular with openbsd I think.  I only pulled it in as a depedancy because networkmgr required it at the time, and it was a quick way to get the job done.  I started using it as a means to launch specific applications such as furybsd-xorg-tool without requiring a password but I know how to accomplish the same thing with sudo.  I would have to say sudo isn't really a linuxism for me as macOS uses it as well.

**Comment by probonopd** [comment]
Indeed. [License](https://www.sudo.ws/license.html) looks BSD-ish too. So sudo it is then. More people know it already.

**Comment by probonopd** [comment]
With both passwords unset, I get an immediate reboot after the ramdisk-backed mount. Do you have an idea why this might be?

**Comment by probonopd** [comment]
I suspect it was an unrelated issue. In any case, I have it working now without `passwords` for root and `liveuser` in my branch.

**Comment by pkgdemon** [comment]
Resolved in https://github.com/furybsd/furybsd-livecd/pull/177
