### ISSUE TITLE
Installed system drops user to console rather than GUI

### ISSUE THREAD

**Issue by probonopd** [furybsd/furybsd-livecd#157]
I am using FuryBSD because I want to be taken straight to a desktop, without having to fiddle around with anything.

Hence I am very disappointed to see that once FuryBSD is installed to hard disk, then it does not automatically boot all the way to a graphical desktop. Instead I have to type in username and password in a non-graphical shell, and then am dropped to a console.

Why can't it just do whatever magic it does in Live mode?

**Comment by probonopd** [comment]
Then, typing `startx` results in "No screens found".
This is exactly the type of stuff that drove my away from FreeBSD in the first place.

**Comment by probonopd** [comment]
NomadBSD works for me in this regard.

**Comment by probonopd** [comment]
What I am looking for is the installed system to behave identically to the Live system.

Possibly this can be achieved by commenting out

https://github.com/furybsd/furybsd-livecd/blob/a0d99d0c6194379559eae14706ffd2735fc94b91/furybsd-install#L35-L53

**Comment by pkgdemon** [comment]
Not sure I agree with this proposal for furybsd at least.  Yes if you want to keep the liveuser you can fork and comment those things out.

**Comment by probonopd** [comment]
@pkgdemon can you confirm that the Xorg setup that works for `liveuser` depends on files in `$HOME`? Could those files be moved somewhere system-wide, so that deleting users can't make or break the working of Xorg?

**Comment by probonopd** [comment]
@pkgdemon I can see your rationale behind not wanting to change too much in the installed system, but I would kindly ask you to reevaluate your stance on this one. Maybe we can find another technical solution to the problem "as a user, I want to install FuryBSD and not lose my working Xorg".

Out of all tickets I have posted here so far, I consider this the most important one - by a long shot.

In fact, it was a make-or-break for me.

For me personally, I now am typing this from a FreeBSD install that originated from NomadBSD rather than FuryBSD because it gave me working Xorg on the installed system immediately, unlike FuryBSD, see https://github.com/furybsd/furybsd-livecd/issues/148#issuecomment-683095074).

A "broken" Xorg is a frustrating experience and not one "mere mortals" ever want to have to deal with.

Possibly the right thing to do is to push the needed changes upstream into FreeBSD?

**Comment by pkgdemon** [comment]
How is it a broken xorg simply because auto login does not work after install?  Is there a separate problem with xorg not working after install?  Are we talking about auto login not working or xorg not working?  Those are two different issues to me.

**Comment by pkgdemon** [comment]
The more I think about it the original request is kind of appealing to me.  We could greatly simplify the install script by just offering to set a root password, offering to replace liveuser with a real one with an auto login option.  I will consider it for next quarter, and think about it some more at least.

**Comment by probonopd** [comment]
> Are we talking about auto login not working or xorg not working? Those are two different issues to me.

I think both things happen, see post 1 and 2 in this ticket.

**Comment by probonopd** [comment]
I suspect that 

```
cp -R ${cwd}/xorg.conf.d/ ${uzip}/usr/home/liveuser/xorg.conf.d
```

is responsible for the working Xorg on the Live ISO while `/home/liveuser` gets deleted as soon as the system is installed to hard disk, hence destroying the once-working Xorg setup?

Would the solution be to put the files into `/usr/local/etc/X11/xorg.conf.d` instead?

**Comment by pkgdemon** [comment]
> I suspect that
> 
> ```
> cp -R ${cwd}/xorg.conf.d/ ${uzip}/usr/home/liveuser/xorg.conf.d
> ```
> 
> is responsible for the working Xorg on the Live ISO while `/home/liveuser` gets deleted as soon as the system is installed to hard disk, hence destroying the once-working Xorg setup?
> 
> Would the solution be to put the files into `/usr/local/etc/X11/xorg.conf.d` instead?

I attempted to do this once long ago with TrueOS however it wouldn't work because xorg would process the files in order, and end up loading scfb for example before intel.  This kind of ties into how we handle overlays, custom applications, update, maintain them.  It really needs a full design doc for I start making a bunch of sweeping changes but let's keep discussing ideas.  The thing is I don't want to get crazy splatting untracked files onto a users system until it's figured out how to maintain changes as needed.

**Comment by probonopd** [comment]
Indeed. What you write matches my observation - just putting the files into `/usr/local/etc/X11/xorg.conf.d` alone did not work in my test.

**Comment by pkgdemon** [comment]
> Indeed. What you write matches my observation - just putting the files into `/usr/local/etc/X11/xorg.conf.d` alone did not work in my test. Still would feel cleaner to me (but then, I haven't fully figured out yet how all of this plays together).

Same which is why it is the way it is now.  I kind of liked the idea of writing /etc/X11/xorg.conf so I could just tell the user to remove if it they have trouble with the failsafe driver, or the stock driver we provided.  The path could be /usr/local/etc/X11/xorg.conf.d/ but most people are not used to that location yet.  It could also just be somewhere in /usr/local/share/examples we have some sample configs that get copied over.  Or some other location such as /opt which is what I was temporarily trying to settle on for FuryBSD specific additions after the removal of ports which didn't work out so well.  I'm currently using /usr/share/skel for things like XFCE settings because the ports maintainers are shipping settings that would override my charges otherwise.  I've considered nuking all of the XFCE settings, custom wallpaper, theme just to present what FreeBSD does out of box, and let the user do their own theming.  That reduce what we have to ship in the repositories, what we have to worry about maintaining, and updating.

**Comment by probonopd** [comment]
> Or some other location such as /opt 

Shouldn't it be `/usr/local/opt` then on FreeBSD?

What do you think about writing a small script that would produce a pkg for the settings, and then have that pkg installed? This way, it could be cleanly uninstalled during installation of the system to hard disk.

Actually, we could have two:
* `furybsd-live.txz` would get uninstalled during installation of the system to hard disk
* `furybsd.txz` would, at least by default, be left installed during installation of the system to hard disk

Since a pkg is just a `.txz` file with some `+MANIFEST` files, it shouldn't be prohibitively hard to put those pkgs together, at least as long as their content is archhitecture-independent. As far as I understand, they also would not need to go into any repo, they would just be generated and installed as part of the ISO generation process. Advantage: Clean, easy to uninstall.

Wdyt?

**Comment by pkgdemon** [comment]
I was already doing ports/pacakges and had an updating script which rebuilt ports on a local machine using git tags.  It might have been simpler to keep it:
https://github.com/furybsd/furybsd-ports

This repo was a problem however because one of the XFCE ports installed the same files to the same location I was:
https://github.com/furybsd/furybsd-xfce-settings/tree/master/etc/xdg/xfce4/xfconf/xfce-perchannel-xml

I could change the desktop settings ports to extract to /usr/share/skel I think with a post install script to resolve that.

**Comment by probonopd** [comment]
Please see https://github.com/furybsd/furybsd-livecd/issues/172 where I propose a solution for this.

**Comment by pkgdemon** [comment]
Resolved in https://github.com/furybsd/furybsd-livecd/pull/177
