### ISSUE TITLE
Intel on EFI: Make screen resolution correct out of the box

### ISSUE THREAD

**Issue by probonopd** [furybsd/furybsd-livecd#190]
With Intel on EFI the screen resolution is correct out of the box only if the bootloader (at the point where you can select extra options) is already shown in the correct resolution. If it is wrong at that point, then it will not be correct on the desktop.

Currently, it is correct in live mode but wrong when installed.

Probably we need to bring over the `/boot/loader.rc` settings from live to installed mode to fix this.

**Comment by probonopd** [comment]
I suspect it has to do with

```
# Decrease boot verbosity and show splash
boot_mute="YES"
beastie_disable="YES"
autoboot_delay=0

# kern.vty=vt
```

which is currently present in Live mode but not in installed mode.

Could be something else though...

**Comment by probonopd** [comment]
Note: In trying to resolve this, don’t use `gop set`.  It might fix one system and will surely break another.

**Comment by probonopd** [comment]
Adding 

```
boot_mute="YES"
beastie_disable="YES"
autoboot_delay=0
```

inded fixes this for me.

**Comment by pkgdemon** [comment]
Yes we just need to work out which settings to transfer over for loader.conf specifically.  I’ll follow up with an example of what is specific to the ramdisk.

**Comment by probonopd** [comment]
I tried as part of furybsd-install:

```
# Transfer settings from running /boot/loader.conf to installed one
# This simplifies things because we have to worry about it only in one place
echo "Applying bootloader configuration"
cp /boot/loader.conf ${FSMNT}/boot
```

But this does not work since in the booted live system there is no `/boot/loader.conf`...

**Comment by probonopd** [comment]
Where does `./overlays/boot/boot/loader.conf` land...?

Ah, it gets copied to cdroot rather than uzip, makes sense.
Where can one access the "CD" from the booted live system?

**Comment by probonopd** [comment]
https://github.com/furybsd/furybsd-livecd/blob/master/overlays/boot/boot/loader.conf#L13

**Comment by probonopd** [comment]
What to put here?

https://github.com/probonopd/temp-installer-gui/blob/cd561f2651538dbd60dbfb43b36e3ca9c8132dce/frontend/furybsd-install#L171

**Comment by pkgdemon** [comment]
> Where does `./overlays/boot/boot/loader.conf` land...?
> 
> Ah, it gets copied to cdroot rather than uzip, makes sense.
> Where can one access the "CD" from the booted live system?

Correct.  You can mount /dev/cd9660/FuryBSD to some mount point. 

These loader tunable needed for Ramdisk init on LiveCD only.  
These should not be used on an installed system.
Everything below this line should move into overlays/boot/boot/loader.conf.local and should not be propagated beyond cdroot.  
Users should understand that changes here affect the livecd boot only.
I would propose splitting these tunable into a few file to help avoid confusion, or how can be better document?

-- BEGIN OF FILE  overlays/boot/boot/loader.conf.local--

geom_uzip_load="YES"
mfsroot_load="YES"
nullfs_load="YES"
tmpfs_load="YES"

mfsroot_type="md_image"
mfsroot_name="/data/ramdisk.ufs"
vfs.root.mountfrom="ufs:/dev/md0"

init_path="/rescue/init"
init_shell="/rescue/sh"
init_script="/init.sh"
init_chroot="/"

kern.geom.label.disk_ident.enable=0
kern.geom.label.gptid.enable=0
kern.geom.label.ufsid.enable=0

# Wait for all device probe to complete before mounting root, even if the
# root device is already available.  This allows to avoid USB probe messages
# printed over the installer menu.  This is needed only in installer with
# its UFS, since ZFS root of installed system implies it automatically.
vfs.root_mount_always_wait="1"

# The following delay during mounting of root file
# system is needed because mounting of an IPMI CD-ROM
# sometimes slow.
vfs.mountroot.timeout="180"

# Disable entropy cache
entropy_cache_load="NO"

# Tune arc for lower memory usage during LiveCD session
vm.kmem_size="330M"
vm.kmem_size_max="330M"
vfs.zfs.arc_max="40M"
vfs.zfs.vdev.cache.size="5M"


-- END OF FILE overlays/boot/boot/loader.conf.local --

These loader tunable values should be used on both livecd boot, and installed system boot.  
Currently a brand new loader.conf is created in /mnt/boot/loader.conf with the following values by line 69 bsdinstall config in this script:
https://github.com/furybsd/furybsd-livecd/blob/master/overlays/uzip/furybsd-live-settings/files/usr/local/bin/furybsd-install#L69
The bsdinstall script populates its values into /tmp which result in opensolaris_load="YES" and zfs_load="YES" getting added which is why we should either populate more of the values below in the installer, or make the build system duplicate the contents of overlays/boot/loader.conf into /uzip/boot/loader.conf and and stop running bsdinstall config, and simply let the installer clone our settings file from the mounted uzip into /mnt/boot/loader.conf.  Or we can make the installer write these additional lines removing opensolaris_load="YES" and zfs_load="YES" since bsdinstall will already write them for us.

Everything below this line should stay in overlays/boot/boot/loader.conf

-- BEGIN OF FILE overlays/boot/boot/loader.conf --

# Decrease boot verbosity and show splash
boot_mute="YES"
beastie_disable="YES"
autoboot_delay=0

# kern.vty=vt # (This one should not be needed if you run kenv it is the default value anyway, and has been for many major versions.)

# Load modules for OpenZFS
opensolaris_load="YES"
zfs_load="YES"

# Add support for I2C devices
ig4_load="YES"
iicbus_load="YES"
iichid_load="YES"

# Prevent panic with intel based network cards
kern.ipc.nmbclusters="1000000"

-- END OF FILE overlays/boot/boot/loader.conf --

**Comment by probonopd** [comment]
Wow, thanks for the a detailed explanation. While I am still trying to wrap my head around it I am confident that you will come up with a great implementation.

**Comment by probonopd** [comment]
I noticed that I get different results depending on what was booted on the machine before (Acer Revo RL85). Strange...
