### ISSUE TITLE
Clear message what the uzipp1 and md2p1 process means

### ISSUE THREAD

**Issue by probonopd** [furybsd/furybsd-livecd#201]
A user thought it was formattnig the disk...

![image](https://user-images.githubusercontent.com/2480569/93629877-4c3d3f80-f9e9-11ea-8227-48670ed6eea1.png)

https://twitter.com/vmlemon/status/1306686274774933505

Should we add some text for "mere mortals" here, e.g.,

> Please wait while the Live system is copied to RAM.
> This is needed until the unionfs kernel driver is fixed.

![image](https://user-images.githubusercontent.com/2480569/93629693-fc5e7880-f9e8-11ea-9784-e5b804f446a9.png)

**Comment by pkgdemon** [comment]
That was added for debugging only.  I was trying do diagnose was boot was failing sometimes.  Which ended up being a build system thing.  This doesn't need to be verbose now I can clean up later.

**Comment by pkgdemon** [comment]
Originally the `zpool status` output above was only added to debug this https://github.com/furybsd/furybsd-livecd/issues/207 when I was working with GhostBSD who were hitting the same issue, and we didn't yet know the culprit (bad uzip, bad usb stick, etc).  Since it has turned out not to be helpful it has been addressed with this commit and other commands such as `gpart` have been silenced as well https://github.com/furybsd/furybsd-livecd/commit/d0b4a1078ea69495a01ebe9d12439fbcc381e554#diff-21a2ed36ff435d1e93caa1a950e3cd55R42.

<img width="1136" alt="Screen Shot 2020-09-27 at 2 47 49 AM" src="https://user-images.githubusercontent.com/4109732/94358042-0f69ec00-006c-11eb-8d25-d12c4ab4fbd5.png">
