### ISSUE TITLE
Workaround for video driver problem on start

### ISSUE THREAD

**Issue by dpostolov** [furybsd/furybsd-livecd#25]
FuryBSD-12.0-XFCE-11-04-2019-01.

Hardware: Intel NUC5PPYH Braswell in EFI mode.

After successfully install and reboot, lightdm don't start.

The workaround:

Add and edit the file:

/usr/local/etc/X11/xorg.conf.d/scfb-driver.conf

Section "Device"
 Identifier "Card0"
 Driver "scfb"
EndSection

**Comment by pkgdemon** [comment]
Hi @dpostolov nice to see you again.  I remember you from the TrueOS project.  This should be fixed in newest ISO.

https://github.com/furybsd/furybsd-livecd/releases/tag/12.0-XFCE-11-06-2019-01

We generat /etc/X11/xorg.conf but it was not getting copied to installed system.

https://github.com/furybsd/furybsd-livecd/commit/e4c15347ea260cc2753b89446cf44803ba16e349

**Comment by pkgdemon** [comment]
There is also a new GUI xorg config tool in this image.  This original problem of scfb not working after install should be resolved.

https://github.com/furybsd/furybsd-livecd/releases/tag/12.0-XFCE-11-09-2019-01
